package com.maxxak.volunteer.repository;

import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import com.maxxak.volunteer.model.User;

//repository interface exptends JPA's data handler
@Repository
public interface UserRepository extends JpaRepository<User, Long> {
    //derived query method generated by Spring to check if username/email already exist in database
    boolean existsByUsername(String username);
    boolean existsByEmail(String email);
    Optional<User> findByEmail(String email);
}
