spring.application.name=volunteer

spring.datasource.url=jdbc:postgresql://localhost:5432/volunteer_platform
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
